create table iegc_violation_message_data(
    ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    message varchar2(20 byte) not null,
    date_time DATE NOT NULL,
    entity VARCHAR2(40 byte),
    schedule NUMBER,
    drawal NUMBER,
    deviation number,
    primary KEY (id),
    UNIQUE(message,date_time,entity)
)